apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ballistics-calculator.fullname" . }}-client
  labels:
    {{- include "ballistics-calculator.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "ballistics-calculator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "ballistics-calculator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
