apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ballistics-calculator.fullname" . }}-config
  labels:
    {{- include "ballistics-calculator.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:{{ .Values.api.service.targetPort }}"
  {{- if .Values.api.corsAllowedOrigins }}
  CorsAllowedOrigins: {{ .Values.api.corsAllowedOrigins | quote }}
  {{- end }}
