apiVersion: v1
kind: Service
metadata:
  name: {{ include "ballistics-calculator.fullname" . }}-postgresql
  labels:
    {{- include "ballistics-calculator.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      protocol: TCP
  selector:
    {{- include "ballistics-calculator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
