apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ballistics-calculator.fullname" . }}-secret
  labels:
    {{- include "ballistics-calculator.labels" . | nindent 4 }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ printf "Host=%s-postgresql;Database=%s;Username=%s;Password=%s" (include "ballistics-calculator.fullname" .) .Values.postgresql.auth.database .Values.postgresql.auth.username .Values.postgresql.auth.password | b64enc | quote }}
  Jwt__Secret: {{ required "api.jwtSecret is required" .Values.api.jwtSecret | b64enc | quote }}
  Jwt__Issuer: {{ .Values.api.jwtIssuer | default "ballistics-api" | b64enc | quote }}
  Jwt__Audience: {{ .Values.api.jwtAudience | default "ballistics-client" | b64enc | quote }}
