api:
  replicaCount: 1
  image:
    repository: ballistics-calculator-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

client:
  replicaCount: 1
  image:
    repository: ballistics-calculator-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

postgresql:
  image:
    repository: postgres
    tag: "16-alpine"
  auth:
    database: ballistics
    username: postgres
    password: postgres
  storage:
    size: 1Gi
  service:
    port: 5432

ingress:
  enabled: true
  className: nginx
  host: ballistics.local
