// <auto-generated />
using BallisticsCalculator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BallisticsCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(BallisticsDbContext))]
    partial class BallisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ballistics")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BallisticsCalculator.Core.Models.Cartridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BallisticCoefficientG1")
                        .HasColumnType("double precision")
                        .HasColumnName("ballistic_coefficient_g1");

                    b.Property<double>("BulletDiameterInches")
                        .HasColumnType("double precision")
                        .HasColumnName("bullet_diameter_inches");

                    b.Property<string>("BulletType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bullet_type");

                    b.Property<double>("BulletWeightGrains")
                        .HasColumnType("double precision")
                        .HasColumnName("bullet_weight_grains");

                    b.Property<double>("BulletWeightGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("bullet_weight_grams");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<double>("MuzzleVelocityFps")
                        .HasColumnType("double precision")
                        .HasColumnName("muzzle_velocity_fps");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cartridges");

                    b.ToTable("cartridges", "ballistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BallisticCoefficientG1 = 0.11899999999999999,
                            BulletDiameterInches = 0.35499999999999998,
                            BulletType = "FMJ",
                            BulletWeightGrains = 95.0,
                            BulletWeightGrams = 6.1600000000000001,
                            Category = "Handgun",
                            MuzzleVelocityFps = 955.0,
                            Name = ".380 ACP 95gr FMJ"
                        },
                        new
                        {
                            Id = 2,
                            BallisticCoefficientG1 = 0.13,
                            BulletDiameterInches = 0.35499999999999998,
                            BulletType = "FMJ",
                            BulletWeightGrains = 115.0,
                            BulletWeightGrams = 7.4500000000000002,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1180.0,
                            Name = "9mm Luger 115gr FMJ"
                        },
                        new
                        {
                            Id = 3,
                            BallisticCoefficientG1 = 0.14299999999999999,
                            BulletDiameterInches = 0.35499999999999998,
                            BulletType = "JHP",
                            BulletWeightGrains = 124.0,
                            BulletWeightGrams = 8.0399999999999991,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1150.0,
                            Name = "9mm Luger 124gr JHP"
                        },
                        new
                        {
                            Id = 4,
                            BallisticCoefficientG1 = 0.16700000000000001,
                            BulletDiameterInches = 0.35499999999999998,
                            BulletType = "JHP",
                            BulletWeightGrains = 147.0,
                            BulletWeightGrams = 9.5299999999999994,
                            Category = "Handgun",
                            MuzzleVelocityFps = 990.0,
                            Name = "9mm Luger 147gr JHP"
                        },
                        new
                        {
                            Id = 5,
                            BallisticCoefficientG1 = 0.14000000000000001,
                            BulletDiameterInches = 0.40000000000000002,
                            BulletType = "FMJ",
                            BulletWeightGrains = 165.0,
                            BulletWeightGrams = 10.69,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1060.0,
                            Name = ".40 S&W 165gr FMJ"
                        },
                        new
                        {
                            Id = 6,
                            BallisticCoefficientG1 = 0.155,
                            BulletDiameterInches = 0.40000000000000002,
                            BulletType = "JHP",
                            BulletWeightGrains = 180.0,
                            BulletWeightGrams = 11.66,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1000.0,
                            Name = ".40 S&W 180gr JHP"
                        },
                        new
                        {
                            Id = 7,
                            BallisticCoefficientG1 = 0.14499999999999999,
                            BulletDiameterInches = 0.45200000000000001,
                            BulletType = "JHP",
                            BulletWeightGrains = 185.0,
                            BulletWeightGrams = 11.99,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1050.0,
                            Name = ".45 ACP 185gr JHP"
                        },
                        new
                        {
                            Id = 8,
                            BallisticCoefficientG1 = 0.19500000000000001,
                            BulletDiameterInches = 0.45200000000000001,
                            BulletType = "FMJ",
                            BulletWeightGrains = 230.0,
                            BulletWeightGrams = 14.9,
                            Category = "Handgun",
                            MuzzleVelocityFps = 830.0,
                            Name = ".45 ACP 230gr FMJ"
                        },
                        new
                        {
                            Id = 9,
                            BallisticCoefficientG1 = 0.14799999999999999,
                            BulletDiameterInches = 0.35699999999999998,
                            BulletType = "JHP",
                            BulletWeightGrains = 125.0,
                            BulletWeightGrams = 8.0999999999999996,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1450.0,
                            Name = ".357 Magnum 125gr JHP"
                        },
                        new
                        {
                            Id = 10,
                            BallisticCoefficientG1 = 0.16400000000000001,
                            BulletDiameterInches = 0.35699999999999998,
                            BulletType = "JSP",
                            BulletWeightGrains = 158.0,
                            BulletWeightGrams = 10.24,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1235.0,
                            Name = ".357 Magnum 158gr JSP"
                        },
                        new
                        {
                            Id = 11,
                            BallisticCoefficientG1 = 0.20499999999999999,
                            BulletDiameterInches = 0.42999999999999999,
                            BulletType = "JSP",
                            BulletWeightGrains = 240.0,
                            BulletWeightGrams = 15.550000000000001,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1350.0,
                            Name = ".44 Magnum 240gr JSP"
                        },
                        new
                        {
                            Id = 12,
                            BallisticCoefficientG1 = 0.16400000000000001,
                            BulletDiameterInches = 0.40000000000000002,
                            BulletType = "FMJ",
                            BulletWeightGrains = 180.0,
                            BulletWeightGrams = 11.66,
                            Category = "Handgun",
                            MuzzleVelocityFps = 1200.0,
                            Name = "10mm Auto 180gr FMJ"
                        },
                        new
                        {
                            Id = 13,
                            BallisticCoefficientG1 = 0.24299999999999999,
                            BulletDiameterInches = 0.224,
                            BulletType = "FMJ",
                            BulletWeightGrains = 55.0,
                            BulletWeightGrams = 3.5600000000000001,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 3240.0,
                            Name = "5.56 NATO 55gr FMJ (M193)"
                        },
                        new
                        {
                            Id = 14,
                            BallisticCoefficientG1 = 0.30399999999999999,
                            BulletDiameterInches = 0.224,
                            BulletType = "FMJ",
                            BulletWeightGrains = 62.0,
                            BulletWeightGrams = 4.0199999999999996,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 3110.0,
                            Name = "5.56 NATO 62gr FMJ (M855)"
                        },
                        new
                        {
                            Id = 15,
                            BallisticCoefficientG1 = 0.255,
                            BulletDiameterInches = 0.224,
                            BulletType = "Polymer Tip",
                            BulletWeightGrains = 55.0,
                            BulletWeightGrams = 3.5600000000000001,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 3240.0,
                            Name = ".223 Rem 55gr V-MAX"
                        },
                        new
                        {
                            Id = 16,
                            BallisticCoefficientG1 = 0.372,
                            BulletDiameterInches = 0.224,
                            BulletType = "BTHP",
                            BulletWeightGrains = 77.0,
                            BulletWeightGrams = 4.9900000000000002,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 2750.0,
                            Name = ".223 Rem 77gr BTHP"
                        },
                        new
                        {
                            Id = 17,
                            BallisticCoefficientG1 = 0.31900000000000001,
                            BulletDiameterInches = 0.308,
                            BulletType = "OTM",
                            BulletWeightGrains = 125.0,
                            BulletWeightGrams = 8.0999999999999996,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 2215.0,
                            Name = ".300 BLK 125gr OTM"
                        },
                        new
                        {
                            Id = 18,
                            BallisticCoefficientG1 = 0.60799999999999998,
                            BulletDiameterInches = 0.308,
                            BulletType = "SMK",
                            BulletWeightGrains = 220.0,
                            BulletWeightGrams = 14.26,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 1010.0,
                            Name = ".300 BLK 220gr SMK Subsonic"
                        },
                        new
                        {
                            Id = 19,
                            BallisticCoefficientG1 = 0.29999999999999999,
                            BulletDiameterInches = 0.312,
                            BulletType = "FMJ",
                            BulletWeightGrains = 123.0,
                            BulletWeightGrams = 7.9699999999999998,
                            Category = "Intermediate",
                            MuzzleVelocityFps = 2350.0,
                            Name = "7.62x39mm 123gr FMJ"
                        },
                        new
                        {
                            Id = 20,
                            BallisticCoefficientG1 = 0.40500000000000003,
                            BulletDiameterInches = 0.24299999999999999,
                            BulletType = "SP",
                            BulletWeightGrains = 100.0,
                            BulletWeightGrams = 6.4800000000000004,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2960.0,
                            Name = ".243 Win 100gr SP"
                        },
                        new
                        {
                            Id = 21,
                            BallisticCoefficientG1 = 0.58499999999999996,
                            BulletDiameterInches = 0.26400000000000001,
                            BulletType = "ELD Match",
                            BulletWeightGrains = 140.0,
                            BulletWeightGrams = 9.0700000000000003,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2710.0,
                            Name = "6.5 Creedmoor 140gr ELD Match"
                        },
                        new
                        {
                            Id = 22,
                            BallisticCoefficientG1 = 0.48599999999999999,
                            BulletDiameterInches = 0.26400000000000001,
                            BulletType = "ELD Match",
                            BulletWeightGrains = 120.0,
                            BulletWeightGrams = 7.7800000000000002,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2910.0,
                            Name = "6.5 Creedmoor 120gr ELD Match"
                        },
                        new
                        {
                            Id = 23,
                            BallisticCoefficientG1 = 0.50600000000000001,
                            BulletDiameterInches = 0.26400000000000001,
                            BulletType = "ELD Match",
                            BulletWeightGrains = 123.0,
                            BulletWeightGrams = 7.9699999999999998,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2580.0,
                            Name = "6.5 Grendel 123gr ELD Match"
                        },
                        new
                        {
                            Id = 24,
                            BallisticCoefficientG1 = 0.40799999999999997,
                            BulletDiameterInches = 0.27700000000000002,
                            BulletType = "SP",
                            BulletWeightGrains = 130.0,
                            BulletWeightGrams = 8.4199999999999999,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 3060.0,
                            Name = ".270 Win 130gr SP"
                        },
                        new
                        {
                            Id = 25,
                            BallisticCoefficientG1 = 0.46500000000000002,
                            BulletDiameterInches = 0.27700000000000002,
                            BulletType = "Partition",
                            BulletWeightGrains = 150.0,
                            BulletWeightGrams = 9.7200000000000006,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2850.0,
                            Name = ".270 Win 150gr Partition"
                        },
                        new
                        {
                            Id = 26,
                            BallisticCoefficientG1 = 0.61299999999999999,
                            BulletDiameterInches = 0.28399999999999997,
                            BulletType = "ELD-X",
                            BulletWeightGrains = 162.0,
                            BulletWeightGrams = 10.5,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2940.0,
                            Name = "7mm Rem Mag 162gr ELD-X"
                        },
                        new
                        {
                            Id = 27,
                            BallisticCoefficientG1 = 0.48499999999999999,
                            BulletDiameterInches = 0.28399999999999997,
                            BulletType = "AccuBond",
                            BulletWeightGrains = 140.0,
                            BulletWeightGrams = 9.0700000000000003,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 3150.0,
                            Name = "7mm Rem Mag 140gr AccuBond"
                        },
                        new
                        {
                            Id = 28,
                            BallisticCoefficientG1 = 0.22600000000000001,
                            BulletDiameterInches = 0.308,
                            BulletType = "Flat Nose",
                            BulletWeightGrains = 150.0,
                            BulletWeightGrams = 9.7200000000000006,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2390.0,
                            Name = ".30-30 Win 150gr FN"
                        },
                        new
                        {
                            Id = 29,
                            BallisticCoefficientG1 = 0.46200000000000002,
                            BulletDiameterInches = 0.308,
                            BulletType = "BTHP",
                            BulletWeightGrains = 168.0,
                            BulletWeightGrams = 10.890000000000001,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2680.0,
                            Name = ".308 Win 168gr BTHP Match"
                        },
                        new
                        {
                            Id = 30,
                            BallisticCoefficientG1 = 0.505,
                            BulletDiameterInches = 0.308,
                            BulletType = "SMK",
                            BulletWeightGrains = 175.0,
                            BulletWeightGrams = 11.34,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2610.0,
                            Name = ".308 Win 175gr SMK"
                        },
                        new
                        {
                            Id = 31,
                            BallisticCoefficientG1 = 0.38700000000000001,
                            BulletDiameterInches = 0.308,
                            BulletType = "SP",
                            BulletWeightGrains = 150.0,
                            BulletWeightGrams = 9.7200000000000006,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2820.0,
                            Name = ".308 Win 150gr SP"
                        },
                        new
                        {
                            Id = 32,
                            BallisticCoefficientG1 = 0.42799999999999999,
                            BulletDiameterInches = 0.308,
                            BulletType = "SP",
                            BulletWeightGrains = 165.0,
                            BulletWeightGrams = 10.69,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2800.0,
                            Name = ".30-06 Springfield 165gr SP"
                        },
                        new
                        {
                            Id = 33,
                            BallisticCoefficientG1 = 0.47399999999999998,
                            BulletDiameterInches = 0.308,
                            BulletType = "Partition",
                            BulletWeightGrains = 180.0,
                            BulletWeightGrams = 11.66,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2700.0,
                            Name = ".30-06 Springfield 180gr Partition"
                        },
                        new
                        {
                            Id = 34,
                            BallisticCoefficientG1 = 0.39300000000000002,
                            BulletDiameterInches = 0.308,
                            BulletType = "FMJ",
                            BulletWeightGrains = 147.0,
                            BulletWeightGrams = 9.5299999999999994,
                            Category = "Standard Rifle",
                            MuzzleVelocityFps = 2800.0,
                            Name = "7.62 NATO 147gr FMJ (M80)"
                        },
                        new
                        {
                            Id = 35,
                            BallisticCoefficientG1 = 0.53300000000000003,
                            BulletDiameterInches = 0.308,
                            BulletType = "BTHP",
                            BulletWeightGrains = 190.0,
                            BulletWeightGrams = 12.31,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2900.0,
                            Name = ".300 Win Mag 190gr BTHP Match"
                        },
                        new
                        {
                            Id = 36,
                            BallisticCoefficientG1 = 0.50700000000000001,
                            BulletDiameterInches = 0.308,
                            BulletType = "AccuBond",
                            BulletWeightGrains = 180.0,
                            BulletWeightGrams = 11.66,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2960.0,
                            Name = ".300 Win Mag 180gr AccuBond"
                        },
                        new
                        {
                            Id = 37,
                            BallisticCoefficientG1 = 0.629,
                            BulletDiameterInches = 0.308,
                            BulletType = "SMK",
                            BulletWeightGrains = 220.0,
                            BulletWeightGrams = 14.26,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2680.0,
                            Name = ".300 Win Mag 220gr SMK"
                        },
                        new
                        {
                            Id = 38,
                            BallisticCoefficientG1 = 0.67500000000000004,
                            BulletDiameterInches = 0.33800000000000002,
                            BulletType = "Scenar",
                            BulletWeightGrains = 250.0,
                            BulletWeightGrams = 16.199999999999999,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2950.0,
                            Name = ".338 Lapua Mag 250gr Scenar"
                        },
                        new
                        {
                            Id = 39,
                            BallisticCoefficientG1 = 0.71999999999999997,
                            BulletDiameterInches = 0.33800000000000002,
                            BulletType = "BTHP",
                            BulletWeightGrains = 300.0,
                            BulletWeightGrams = 19.440000000000001,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2750.0,
                            Name = ".338 Lapua Mag 300gr BTHP"
                        },
                        new
                        {
                            Id = 40,
                            BallisticCoefficientG1 = 0.55000000000000004,
                            BulletDiameterInches = 0.33800000000000002,
                            BulletType = "AccuBond",
                            BulletWeightGrains = 225.0,
                            BulletWeightGrams = 14.58,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2785.0,
                            Name = ".338 Win Mag 225gr AccuBond"
                        },
                        new
                        {
                            Id = 41,
                            BallisticCoefficientG1 = 0.47999999999999998,
                            BulletDiameterInches = 0.375,
                            BulletType = "DGX",
                            BulletWeightGrains = 300.0,
                            BulletWeightGrams = 19.440000000000001,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2530.0,
                            Name = ".375 H&H Mag 300gr DGX"
                        },
                        new
                        {
                            Id = 42,
                            BallisticCoefficientG1 = 0.67000000000000004,
                            BulletDiameterInches = 0.51000000000000001,
                            BulletType = "FMJ",
                            BulletWeightGrains = 660.0,
                            BulletWeightGrams = 42.770000000000003,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2910.0,
                            Name = ".50 BMG 660gr FMJ (M33)"
                        },
                        new
                        {
                            Id = 43,
                            BallisticCoefficientG1 = 1.05,
                            BulletDiameterInches = 0.51000000000000001,
                            BulletType = "A-MAX",
                            BulletWeightGrains = 750.0,
                            BulletWeightGrams = 48.600000000000001,
                            Category = "Magnum",
                            MuzzleVelocityFps = 2820.0,
                            Name = ".50 BMG 750gr A-MAX"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
