FROM node:20-alpine AS build
WORKDIR /app

COPY src/BallisticsCalculator.Client/package.json src/BallisticsCalculator.Client/package-lock.json ./
RUN npm ci

COPY src/BallisticsCalculator.Client/ ./
RUN npm run build

FROM nginx:alpine AS runtime

COPY src/BallisticsCalculator.Client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
